"""Summarise the reduced-design training arms, tier by tier.

Reports mean +/- 95% bootstrap CI of final evaluation return per arm, and the
paired contrasts each tier exists to answer. The tier-1 contrast is a gate:
if dense attention-comm does not beat comm-free MAPPO on a task where the
channel is necessary, nothing measured in tiers 2-4 is interpretable
(D-011, D-027).
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import statistics
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "results"

# The comparisons the design was built to make. (name, arm_a, arm_b) reads
# "does arm_a beat arm_b, and by how much".
CONTRASTS = [
    (1, "channel works on simple_reference", "red_ref_dense", "red_ref_mappo"),
    (1, "channel works on PO simple_spread N=6", "red_po6_dense", "red_po6_mappo"),
    (2, "does WHICH peers matter (k=2)", "red_po6_gather_k2", "red_po6_random_k2"),
    (2, "cost of sparsifying to k=2", "red_po6_gather_k2", "red_po6_dense"),
    (3, "k=1 vs k=4", "red_po6_gather_k1", "red_po6_gather_k4"),
    (3, "N=12 sparsification cost", "red_po12_gather_k3", "red_po12_dense"),
    (4, "Lagrangian budget vs dense", "red_po6_lagrangian", "red_po6_dense"),
    (4, "entmax vs dense", "red_po6_entmax", "red_po6_dense"),
]


def final_returns(arm: str) -> list[float]:
    """Final eval return per seed, preferring final_eval.json over the CSV."""
    out = []
    for seed_dir in sorted((R / arm).glob("seed_*")) if (R / arm).exists() else []:
        fe = seed_dir / "final_eval.json"
        if fe.exists():
            d = json.loads(fe.read_text())
            v = d.get("eval_return_mean", d.get("return_mean"))
            if v is not None:
                out.append(float(v))
                continue
        csv_p = seed_dir / "metrics.csv"
        if csv_p.exists():
            rows = [r for r in csv.DictReader(csv_p.open())
                    if r.get("eval_return_mean")]
            if rows:
                out.append(float(rows[-1]["eval_return_mean"]))
    return out


def boot_ci(vals: list[float], reps: int = 10_000,
            seed: int = 0) -> tuple[float, float]:
    if len(vals) < 2:
        return (float("nan"), float("nan"))
    rng = random.Random(seed)
    means = sorted(statistics.fmean(rng.choices(vals, k=len(vals)))
                   for _ in range(reps))
    return (means[int(0.025 * reps)], means[int(0.975 * reps)])


def mech(arm: str) -> dict[str, float]:
    """Mean of the mechanism columns over the last decile of training."""
    vals: dict[str, list[float]] = {}
    for seed_dir in sorted((R / arm).glob("seed_*")) if (R / arm).exists() else []:
        csv_p = seed_dir / "metrics.csv"
        if not csv_p.exists():
            continue
        rows = list(csv.DictReader(csv_p.open()))
        for row in rows[max(0, int(len(rows) * 0.9)):]:
            for key in ("mean_k", "attn_entropy", "lagrange_lambda"):
                if row.get(key):
                    vals.setdefault(key, []).append(float(row[key]))
    return {k: statistics.fmean(v) for k, v in vals.items() if v}


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", default=str(R / "reduced_design_summary.md"))
    args = p.parse_args()

    manifest = json.loads((ROOT / "configs" / "reduced" / "MANIFEST.json").read_text())
    lines = ["# Reduced design — results", "",
             "Generated by `scripts/summarise_reduced_design.py`. "
             "CIs are 95% bootstrap over seeds.", "",
             "| Tier | Arm | seeds | final return | 95% CI | mean_k | "
             "attn entropy | lambda |", "|---|---|---|---|---|---|---|---|"]

    data: dict[str, list[float]] = {}
    for a in manifest["arms"]:
        arm = a["run_name"]
        vals = final_returns(arm)
        data[arm] = vals
        m = mech(arm)
        if not vals:
            lines.append(f"| {a['tier']} | `{arm}` | 0 | _not run_ | — | — | — | — |")
            continue
        lo, hi = boot_ci(vals)
        lines.append(
            f"| {a['tier']} | `{arm}` | {len(vals)} | "
            f"{statistics.fmean(vals):.2f} | [{lo:.2f}, {hi:.2f}] | "
            f"{m.get('mean_k', float('nan')):.2f} | "
            f"{m.get('attn_entropy', float('nan')):.2f} | "
            f"{m.get('lagrange_lambda', float('nan')):.2f} |")

    lines += ["", "## Contrasts the design exists to make", "",
              "| Tier | Question | A | B | A-B | 95% CI of difference | "
              "verdict |", "|---|---|---|---|---|---|---|"]
    for tier, q, a_name, b_name in CONTRASTS:
        a_vals, b_vals = data.get(a_name, []), data.get(b_name, [])
        if len(a_vals) < 2 or len(b_vals) < 2:
            lines.append(f"| {tier} | {q} | `{a_name}` | `{b_name}` | "
                         f"_incomplete_ | — | — |")
            continue
        diff = statistics.fmean(a_vals) - statistics.fmean(b_vals)
        rng = random.Random(0)
        diffs = sorted(
            statistics.fmean(rng.choices(a_vals, k=len(a_vals)))
            - statistics.fmean(rng.choices(b_vals, k=len(b_vals)))
            for _ in range(10_000))
        lo, hi = diffs[250], diffs[9750]
        verdict = ("A > B" if lo > 0 else "B > A" if hi < 0
                   else "no separation")
        lines.append(f"| {tier} | {q} | `{a_name}` | `{b_name}` | "
                     f"{diff:+.2f} | [{lo:+.2f}, {hi:+.2f}] | {verdict} |")

    lines += ["", "**Gate:** the tier-1 rows must read `A > B`. If they do "
              "not, the communication channel is not carrying information on "
              "a task that requires it, and no sparsification result from "
              "tiers 2-4 can be interpreted (D-011).", ""]

    Path(args.out).write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
